# Generated by Django 4.1.3 on 2023-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='country',
            field=models.CharField(max_length=35),
        ),
    ]
