# Generated by Django 4.2.6 on 2023-10-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_details_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='country',
        ),
        migrations.RemoveField(
            model_name='details',
            name='state',
        ),
    ]
