# Generated by Django 4.1.3 on 2023-10-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_doctors_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appdate',
            field=models.DateField(),
        ),
    ]
