# Generated by Django 4.1.3 on 2023-10-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_appointments_appdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appdate',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='apptime',
            field=models.CharField(max_length=5),
        ),
    ]
