# Generated by Django 4.1.3 on 2023-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_appointments_appdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='desc',
            field=models.CharField(default='COLD', max_length=150),
            preserve_default=False,
        ),
    ]
