# Generated by Django 4.1.3 on 2023-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_appointments_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='docid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='pid',
            field=models.IntegerField(),
        ),
    ]
