# Generated by Django 4.2.6 on 2023-11-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_appointments_docid_alter_appointments_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminlog',
            fields=[
                ('adid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
