# Generated by Django 4.2.6 on 2023-11-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_adminlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
