# Generated by Django 4.2.6 on 2023-11-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_delete_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('docid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=40)),
                ('appdate', models.CharField(max_length=8)),
                ('apptime', models.CharField(max_length=5)),
                ('desc', models.CharField(max_length=150)),
            ],
        ),
    ]
