# Generated by Django 4.2.6 on 2023-11-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='docname',
            field=models.CharField(default='Doctor uhh', max_length=40),
            preserve_default=False,
        ),
    ]
