# Generated by Django 4.1.3 on 2023-11-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_appointments_docname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
