# Generated by Django 4.1.3 on 2023-11-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_delete_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('docid', models.IntegerField()),
                ('docname', models.CharField(max_length=40)),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=40)),
                ('appdate', models.DateTimeField()),
                ('desc', models.CharField(max_length=150)),
            ],
        ),
    ]
